project_id = "jktklzddcmazfmwlfoas"

[auth]
enable_signup = false
enable_confirmations = true
enable_manual_linking = false

[functions.issue-livekit-token]
verify_jwt = false

[functions.admin-invite-user]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-set-user-status]
verify_jwt = false

[functions.admin-room-action]
verify_jwt = false

[functions.livekit-webhook]
verify_jwt = false

[functions.channel-action]
verify_jwt = false

[functions.admin-set-user-role]
verify_jwt = false

[functions.enforce-call-limits]
verify_jwt = false

[functions.admin-usage-summary]
verify_jwt = false

[functions.admin-call-settings]
verify_jwt = false

[functions.channel-presence]
verify_jwt = false

[functions.social-action]
verify_jwt = false
