import { useEffect, useMemo, useRef, useState, type ChangeEvent, type CSSProperties, type FormEvent } from 'react'
import { primeCallSounds } from '../../services/callSounds'
import { normalizeDisplayName } from '../../services/livekit'
import { normalizeProfileNameStyle, prepareProfileAvatar } from '../../services/profile'
import type { AccountProfile, ChannelCallSummary, ChannelPresence, ChannelSummary, ConnectionStatus, ContextMenuPoint, LocalProfile, ProfileNameStyle, RecognizedActivity, SocialOverview } from '../../types'
import { BrandMark } from '../ui/BrandMark'
import { Icon } from '../ui/Icon'
import { ProfileAvatar } from '../ui/ProfileAvatar'
import { StyledProfileName } from '../ui/StyledProfileName'
import { AppSettingsScreen } from '../Settings/AppSettingsScreen'
import { FriendsWorkspace } from '../Friends/FriendsWorkspace'

interface Props {
  status: ConnectionStatus; connectionError: string; initialChannelId: string; channels: ChannelSummary[]; presence: ChannelPresence[]
  canCreateChannel: boolean; profile: AccountProfile; isAdmin: boolean; onOpenAdmin: () => void
  onCreateChannel: (name: string) => Promise<ChannelSummary>; onRenameChannel: (id: string, name: string) => Promise<ChannelSummary>
  onCreateCall: (channelId: string, name: string) => Promise<ChannelCallSummary>
  onCreateInvite: (channelId: string) => Promise<string>
  onArchiveChannel: (id: string) => Promise<void>; onLogout: () => Promise<void>
  onJoin: (profile: LocalProfile, id: string, channelId?: string) => Promise<boolean>; onProfileChange: (profile: LocalProfile) => Promise<AccountProfile | null>
  onUsernameChange: (username: string) => Promise<AccountProfile | null>
  initialView?: 'home' | 'channel' | 'profile' | 'settings'
  activitySharingEnabled: boolean
  activity?: RecognizedActivity
  canHighQualityScreenShare: boolean
  onActivitySharingChange: (enabled: boolean) => void
  social: SocialOverview
  onRefreshSocial: () => Promise<void>
}
type View = 'home' | 'channel' | 'friends' | 'profile' | 'settings'
const roleLabel = (role: AccountProfile['role']) => ({ owner: 'Proprietário', manager: 'Gerente', host: 'Host', member: 'Membro' }[role])
const initials = (name: string) => name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase()).join('') || '#'

const ChannelInfoCard = ({ channel, live, onOpen }: { channel: ChannelSummary; live?: ChannelPresence; onOpen: () => void }) => {
  const activities = (live?.participants || []).filter((participant) => participant.activity)
  const participants = live?.participants || []
  return <button onClick={onOpen} type="button">
    <div className="channel-home__card-top"><span className="channel-home__channel-mark">{initials(channel.name)}</span><span className={`channel-home__card-status${channel.participantCount ? ' is-live' : ''}`}>{channel.participantCount ? 'AO VIVO' : 'DISPONÍVEL'}</span></div>
    <h2>{channel.name}</h2>
    <div className={`channel-home__card-activity${activities.length ? ' is-active' : ''}`}><span>{activities.length ? 'AGORA NO CANAL' : 'ATIVIDADE'}</span>{activities.length ? activities.slice(0, 2).map((participant) => <p key={participant.userId || participant.displayName}><b>{participant.activity?.kind === 'game' ? 'Jogando' : 'Usando'} {participant.activity?.displayName}</b><StyledProfileName style={participant.nameStyle}>{participant.displayName}</StyledProfileName></p>) : <p><b>Nenhuma atividade agora</b></p>}</div>
    <div className="channel-home__card-metrics"><span><Icon name="users" /><strong>{channel.participantCount}</strong><small>na call</small></span><span><Icon name="audio" /><strong>{channel.participantCount ? 1 : 0}</strong><small>call</small></span><span><Icon name="screen" /><strong>{live?.screenSharing ? 'Sim' : 'Não'}</strong><small>tela</small></span></div>
    <div className="channel-home__card-people"><div>{participants.slice(0, 6).map((participant) => <span className="channel-home__member-avatar is-online" key={participant.userId || participant.displayName} title={`${participant.displayName} · na call`}><ProfileAvatar avatarDataUrl={participant.avatarDataUrl} name={participant.displayName} /></span>)}{participants.length > 6 && <b>+{participants.length - 6}</b>}{!participants.length && <small>Ninguém na call agora</small>}</div><span>Ver canal <Icon name="chevron" /></span></div>
  </button>
}

export const LobbyWorkspace = ({ status, connectionError, initialChannelId, initialView, channels, presence, canCreateChannel, canHighQualityScreenShare, profile, isAdmin, activity, activitySharingEnabled, onActivitySharingChange, onOpenAdmin, onCreateChannel, onCreateCall, onCreateInvite, onRenameChannel, onArchiveChannel, onLogout, onJoin, onProfileChange, onUsernameChange, social, onRefreshSocial }: Props) => {
  const [view, setView] = useState<View>(initialView || (initialChannelId ? 'channel' : 'home'))
  const [channelId, setChannelId] = useState(initialChannelId)
  const [creating, setCreating] = useState(false)
  const [newName, setNewName] = useState('')
  const [renameName, setRenameName] = useState('')
  const [callName, setCallName] = useState('')
  const [selectedCallId, setSelectedCallId] = useState('')
  const [channelMenu, setChannelMenu] = useState<{ channelId: string; point: ContextMenuPoint } | null>(null)
  const [channelMenuAction, setChannelMenuAction] = useState<'call' | 'rename' | null>(null)
  const [toast, setToast] = useState('')
  const [message, setMessage] = useState('')
  const [profileName, setProfileName] = useState(profile.displayName)
  const [profileUsername, setProfileUsername] = useState(profile.username || '')
  const [profileAvatar, setProfileAvatar] = useState(profile.avatarDataUrl)
  const [profileStyle, setProfileStyle] = useState<ProfileNameStyle>(normalizeProfileNameStyle(profile.nameStyle))
  const [profileBusy, setProfileBusy] = useState(false)
  const createInput = useRef<HTMLInputElement>(null)
  const presenceMap = useMemo(() => new Map(presence.map((item) => [item.channelId, item])), [presence])
  const selected = channels.find((channel) => channel.id === channelId)
  const selectedPresence = selected ? presenceMap.get(selected.id) : undefined
  const selectedCall = selected?.calls?.find((call) => call.id === selectedCallId) || selected?.calls?.[0]
  const selectedCallPresence = selectedPresence?.calls?.find((call) => call.callId === selectedCall?.id)
  const connecting = status === 'connecting' || status === 'reconnecting'

  useEffect(() => { if (creating) window.setTimeout(() => createInput.current?.focus(), 50) }, [creating])
  useEffect(() => { setMessage(''); setRenameName('') }, [view, channelId])
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 4200); return () => window.clearTimeout(timer) }, [toast])
  useEffect(() => { setProfileName(profile.displayName); setProfileUsername(profile.username || ''); setProfileAvatar(profile.avatarDataUrl); setProfileStyle(normalizeProfileNameStyle(profile.nameStyle)) }, [profile])
  useEffect(() => { if (!initialView && initialChannelId && channels.some((channel) => channel.id === initialChannelId)) { setChannelId(initialChannelId); setView('channel') } }, [channels, initialChannelId, initialView])
  useEffect(() => {
    if (!selected?.calls?.length) { setSelectedCallId(''); return }
    if (!selected.calls.some((call) => call.id === selectedCallId)) setSelectedCallId(selected.calls[0].id)
  }, [selected, selectedCallId])

  const openChannel = (id: string) => { const channel = channels.find((item) => item.id === id); setChannelId(id); setSelectedCallId(channel?.calls?.[0]?.id || ''); setView('channel') }
  const create = async (event: FormEvent) => { event.preventDefault(); if (!newName.trim()) return; try { const channel = await onCreateChannel(newName.trim()); setNewName(''); setCreating(false); openChannel(channel.id) } catch { setMessage('Não foi possível criar esse canal.') } }
  const rename = async (event: FormEvent, id = selected?.id) => { event.preventDefault(); if (!id || !renameName.trim()) return; try { await onRenameChannel(id, renameName.trim()); setRenameName(''); setChannelMenu(null); setChannelMenuAction(null); setToast('Canal renomeado com sucesso.') } catch { setMessage('Não foi possível renomear esse canal.') } }
  const addCall = async (event: FormEvent, id = selected?.id) => { event.preventDefault(); if (!id || !callName.trim()) return; try { const call = await onCreateCall(id, callName.trim()); setCallName(''); setSelectedCallId(call.id); setChannelMenu(null); setChannelMenuAction(null); setToast('Nova call criada no canal.') } catch { setMessage('Não foi possível criar essa call.') } }
  const invite = async (channelId: string) => { try { const link = await onCreateInvite(channelId); try { await navigator.clipboard.writeText(link) } catch { const area = document.createElement('textarea'); area.value = link; area.style.position = 'fixed'; area.style.opacity = '0'; document.body.appendChild(area); area.focus(); area.select(); document.execCommand('copy'); area.remove() }; setToast('Convite copiado para a área de transferência.'); setChannelMenu(null); setChannelMenuAction(null) } catch { setMessage('Não foi possível criar o convite.') } }
  const archive = async (target = selected) => { if (!target || !window.confirm(`Arquivar ${target.name}?`)) return; try { await onArchiveChannel(target.id); setChannelMenu(null); setChannelMenuAction(null); if (target.id === channelId) { setChannelId(''); setView('home') }; setToast('Canal arquivado.') } catch { setMessage('Não foi possível arquivar esse canal.') } }
  const join = async (callId = selectedCall?.id) => { if (!selected || !callId) return; const local = { displayName: normalizeDisplayName(profile.displayName), avatarDataUrl: profile.avatarDataUrl, nameStyle: profile.nameStyle }; if (!local.displayName) { setMessage('Seu perfil ainda não possui um nome.'); return } primeCallSounds(); await onJoin(local, callId, selected.id) }
  const chooseAvatar = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { setProfileBusy(true); setProfileAvatar(await prepareProfileAvatar(file)); setMessage('') } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível preparar essa imagem.') } finally { setProfileBusy(false) } }
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); const displayName = normalizeDisplayName(profileName); const username = profileUsername.trim().toLowerCase().replace(/^@/, ''); if (!displayName) return setMessage('Informe um nome visível.'); if (!/^[a-z0-9_]{3,24}$/.test(username)) return setMessage('Use um @username de 3 a 24 caracteres: letras minúsculas, números ou _.'); setProfileBusy(true); const usernameSaved = username === profile.username || await onUsernameChange(username); const saved = usernameSaved ? await onProfileChange({ displayName, avatarDataUrl: profileAvatar, nameStyle: profileStyle }) : null; setProfileBusy(false); if (saved) { setMessage(''); setView('home') } else setMessage('Não foi possível salvar seu perfil agora.') }

  return <main className="channel-home"><div className="channel-home__grid" aria-hidden="true" />
    <aside className="channel-home__sidebar"><header className="channel-home__brand"><BrandMark /><div><p>PRIVATE COMMS</p><strong>SPLOTYS</strong></div></header>
      <button className={`channel-home__home-link${view === 'home' ? ' is-active' : ''}`} onClick={() => setView('home')} type="button"><span><Icon name="layout" /></span><strong>Home</strong><small>Visão geral</small></button>
      <button className={`channel-home__home-link channel-home__friends-link${view === 'friends' ? ' is-active' : ''}`} onClick={() => setView('friends')} type="button"><span><Icon name="users" /></span><strong>Amigos</strong><small>Conversas privadas</small>{(social.incoming.length + social.conversations.reduce((total, item) => total + item.unreadCount, 0)) > 0 && <b className="channel-home__social-badge">{Math.min(99, social.incoming.length + social.conversations.reduce((total, item) => total + item.unreadCount, 0))}{(social.incoming.length + social.conversations.reduce((total, item) => total + item.unreadCount, 0)) > 99 ? '+' : ''}</b>}</button>
      <div className="channel-home__channel-heading"><span>Seus canais</span><div><b>{channels.length}</b>{canCreateChannel && <button aria-label="Criar novo canal" className={creating ? 'is-active' : ''} onClick={() => setCreating((value) => !value)} type="button">+</button>}</div></div>
      <nav className="channel-home__channel-list">{channels.map((channel) => <button className={view === 'channel' && channel.id === channelId ? 'is-active' : ''} key={channel.id} onClick={() => openChannel(channel.id)} onContextMenu={(event) => { event.preventDefault(); setChannelMenu({ channelId: channel.id, point: { x: event.clientX, y: event.clientY } }) }} type="button"><span className="channel-home__channel-mark">{initials(channel.name)}</span><span className="channel-home__channel-copy"><strong>{channel.name}</strong><small>{channel.participantCount ? `${channel.participantCount} na call` : 'Canal disponível'}</small></span><span className={`channel-home__presence${channel.participantCount ? ' is-live' : ''}`} /></button>)}</nav>
      {channelMenu && (() => { const menuChannel = channels.find((channel) => channel.id === channelMenu.channelId); if (!menuChannel?.canManage) return null; return <><button aria-label="Fechar menu do canal" className="context-menu-backdrop" onClick={() => { setChannelMenu(null); setChannelMenuAction(null) }} type="button" /><section aria-label={`Opções de ${menuChannel.name}`} className="context-menu channel-context-menu" onContextMenu={(event) => event.preventDefault()} style={{ left: Math.min(channelMenu.point.x, window.innerWidth - 300), top: Math.min(channelMenu.point.y, window.innerHeight - 260) }}><header><span><strong>{menuChannel.name}</strong><small>Opções do canal</small></span><Icon name="controls" /></header>{channelMenuAction === 'call' ? <form className="channel-context-menu__form" onSubmit={(event) => void addCall(event, menuChannel.id)}><label>Nova call</label><div><input autoFocus maxLength={48} onChange={(event) => setCallName(event.target.value)} placeholder="Ex.: Sala de jogos" value={callName} /><button disabled={!callName.trim()} type="submit">Criar</button></div></form> : channelMenuAction === 'rename' ? <form className="channel-context-menu__form" onSubmit={(event) => void rename(event, menuChannel.id)}><label>Renomear canal</label><div><input autoFocus maxLength={48} onChange={(event) => setRenameName(event.target.value)} placeholder={menuChannel.name} value={renameName} /><button disabled={!renameName.trim()} type="submit">Salvar</button></div></form> : <><button onClick={() => void invite(menuChannel.id)} type="button"><Icon name="send" />Criar convite</button><button onClick={() => setChannelMenuAction('call')} type="button"><Icon name="audio" />Nova call</button><button onClick={() => setChannelMenuAction('rename')} type="button"><Icon name="settings" />Renomear canal</button><div className="channel-context-menu__divider" /><button className="channel-context-menu__danger" onClick={() => void archive(menuChannel)} type="button"><Icon name="warning" />Arquivar canal</button></>}</section></> })()}
      {creating && <form className="channel-home__creator" onSubmit={(event) => void create(event)}><label>Novo canal</label><input maxLength={48} onChange={(event) => setNewName(event.target.value)} placeholder="Ex.: Resenha da noite" ref={createInput} value={newName} /><div><button onClick={() => setCreating(false)} type="button">Cancelar</button><button disabled={!newName.trim()} type="submit">Criar</button></div></form>}
      <footer className="call-sidebar-profile"><button className="call-sidebar-profile__identity" onClick={() => setView('profile')} type="button"><ProfileAvatar avatarDataUrl={profile.avatarDataUrl} name={profile.displayName || 'Você'} /><span><StyledProfileName style={profile.nameStyle}>{profile.displayName || 'Seu perfil'}</StyledProfileName><small className={activity ? 'has-activity' : ''}>{activity?.iconDataUrl && <img alt="" src={activity.iconDataUrl} />}{activity ? `${activity.kind === 'game' ? 'Jogando' : 'Usando'} ${activity.displayName}` : `${roleLabel(profile.role)} · editar perfil`}</small></span><Icon name="chevron" /></button><button aria-label="Abrir configurações" className={view === 'settings' ? 'is-active' : ''} onClick={() => setView('settings')} title="Configurações" type="button"><Icon name="settings" /></button></footer>
    </aside>
    <section className="channel-home__main"><header className="channel-home__topbar"><div className="channel-home__breadcrumb"><span className="channel-home__secure-dot" />{view === 'channel' && selected ? <><strong>{selected.name}</strong><Icon name="chevron" /><span>Calls</span>{selectedCall && <><Icon name="chevron" /><em>{selectedCall.name}</em></>}</> : view === 'friends' ? <><strong>Amigos</strong><Icon name="chevron" /><span>Conversas privadas</span></> : <span>Sessão protegida</span>}</div><nav>{isAdmin && <button onClick={onOpenAdmin} type="button"><Icon name="settings" /> Painel admin</button>}<button onClick={() => void onLogout()} type="button">Sair</button></nav></header>
      {view === 'home' && <div className="channel-home__dashboard"><header><p className="eyebrow">SUA BASE DE CONVERSAS</p><h1>Boa noite, <StyledProfileName style={profile.nameStyle}>{profile.displayName.split(/\s+/)[0] || 'você'}</StyledProfileName>.</h1><p>Veja rapidamente onde o pessoal está e o que está acontecendo agora.</p></header><div className="channel-home__cards">{channels.map((channel) => <ChannelInfoCard channel={channel} key={channel.id} live={presenceMap.get(channel.id)} onOpen={() => openChannel(channel.id)} />)}{!channels.length && <div className="channel-home__dashboard-empty"><BrandMark /><h2>Ainda não há canais.</h2><p>{canCreateChannel ? 'Crie o primeiro pelo botão + na barra lateral.' : 'Assim que um host criar um, ele aparecerá aqui.'}</p></div>}</div></div>}
      {view === 'channel' && selected && <div className="channel-workspace">
        <aside className="channel-workspace__calls">
          <header className="channel-workspace__channel-header"><span className="channel-home__channel-mark">{initials(selected.name)}</span><div><small>CANAL</small><strong>{selected.name}</strong><span><i className={selected.participantCount ? 'is-live' : ''} />{selected.participantCount ? `${selected.participantCount} em call` : 'Disponível'}</span></div></header>
          <div className="channel-workspace__calls-heading"><span>Calls</span><b>{selected.calls?.length || 0}</b></div>
          <nav className="channel-workspace__call-list" aria-label={`Calls de ${selected.name}`}>{(selected.calls || []).map((call) => { const liveCall = selectedPresence?.calls?.find((item) => item.callId === call.id); const participants = liveCall?.participants || []; const isActive = selectedCall?.id === call.id; return <button className={isActive ? 'is-active' : ''} key={call.id} onClick={() => setSelectedCallId(call.id)} type="button"><span className="channel-workspace__call-icon"><Icon name="audio" /></span><span className="channel-workspace__call-copy"><strong>{call.name}</strong><small>{participants.length ? `${participants.length} conversando` : 'Sala disponível'}</small></span>{participants.length > 0 && <span className="channel-workspace__call-count">{participants.length}</span>}<Icon name="chevron" />{participants.length > 0 && <span className="channel-workspace__call-members">{participants.slice(0, 6).map((participant) => <span key={participant.userId || `${participant.displayName}-${participant.joinedAt}`}><ProfileAvatar avatarDataUrl={participant.avatarDataUrl} name={participant.displayName} /><StyledProfileName style={participant.nameStyle}>{participant.displayName}</StyledProfileName>{participant.screenSharing && <em title="Transmitindo"><Icon name="screen" /></em>}</span>)}</span>}</button> })}</nav>
          {!selected.calls?.length && <div className="channel-workspace__no-calls"><Icon name="audio" /><strong>Nenhuma call</strong><small>{selected.canManage ? 'Abra o gerenciamento para criar a primeira.' : 'O proprietário ainda não criou uma call.'}</small></div>}
          <footer><Icon name="users" /><span><strong>{selected.participantCount}</strong><small>pessoas no canal</small></span><Icon name="screen" /><span><strong>{selectedPresence?.screenSharing ? 'Ao vivo' : 'Inativa'}</strong><small>transmissão</small></span></footer>
        </aside>
        <section className="call-preview">
          {selectedCall ? <><header><div><span className={`call-preview__live${selectedCallPresence?.participantCount ? ' is-live' : ''}`}><i />{selectedCallPresence?.participantCount ? 'CALL EM ANDAMENTO' : 'CALL DISPONÍVEL'}</span><h1>{selectedCall.name}</h1><p>Call de voz em <strong>{selected.name}</strong></p></div><span className="call-preview__room-mark"><Icon name="audio" /></span></header>
            <div className="call-preview__overview"><span><Icon name="users" /><strong>{selectedCallPresence?.participantCount || 0}</strong><small>na call</small></span><span><Icon name="screen" /><strong>{selectedCallPresence?.participants.some((participant) => participant.screenSharing) ? 'Ativa' : 'Inativa'}</strong><small>transmissão</small></span><span><Icon name="audio" /><strong>Voz</strong><small>áudio protegido</small></span></div>
            <section className="call-preview__people"><header><div><span>Pessoas nesta call</span><small>Quem entrar aparece aqui em tempo real</small></div><b>{selectedCallPresence?.participants.length || 0}</b></header>{selectedCallPresence?.participants.length ? <div>{selectedCallPresence.participants.map((participant) => <article key={participant.userId || `${participant.displayName}-${participant.joinedAt}`}><ProfileAvatar avatarDataUrl={participant.avatarDataUrl} name={participant.displayName} /><span><StyledProfileName style={participant.nameStyle}>{participant.displayName}</StyledProfileName><small>{participant.activity ? `${participant.activity.kind === 'game' ? 'Jogando' : 'Usando'} ${participant.activity.displayName}` : 'Na call agora'}</small></span>{participant.screenSharing && <em><Icon name="screen" /> Ao vivo</em>}</article>)}</div> : <div className="call-preview__empty-people"><span><Icon name="users" /></span><strong>A sala está silenciosa</strong><small>Seja a primeira pessoa a entrar nesta call.</small></div>}</section>
            {(message || connectionError) && <div className="inline-error channel-home__error"><Icon name="warning" /><span>{message || connectionError}</span></div>}
            <footer className="call-preview__footer"><div><span className="channel-home__secure-dot" /><span><strong>Conexão protegida</strong><small>Áudio e presença em tempo real</small></span></div><button className="channel-home__join" disabled={connecting} onClick={() => void join(selectedCall.id)} type="button"><span className="channel-home__join-icon"><Icon name="audio" /></span><span><strong>{connecting ? 'Entrando…' : 'Entrar na call'}</strong><small>{selectedCall.name}</small></span><Icon name="chevron" /></button></footer></> : <div className="call-preview__empty"><span><Icon name="audio" /></span><p className="eyebrow">CANAL PRONTO</p><h1>Escolha uma call.</h1><p>As calls deste canal aparecem na coluna ao lado. Quando uma for criada, você poderá ver quem está nela antes de entrar.</p></div>}
        </section>
      </div>}
      {view === 'friends' && <FriendsWorkspace onRefresh={onRefreshSocial} overview={social} profile={profile} />}
      {view === 'profile' && <div className="profile-studio">
        <header className="profile-studio__header"><div><button onClick={() => setView('home')} type="button"><Icon name="chevron" /> Voltar</button><p className="eyebrow">ESTÚDIO DE IDENTIDADE</p><h1>Faça seu nome ter presença.</h1><p>Monte uma assinatura visual que acompanha você nos canais, chats e calls.</p></div><span><Icon name="layout" /></span></header>
        <form className="profile-studio__layout" onSubmit={(event) => void saveProfile(event)}>
          <aside className="profile-studio__preview">
            <div className="profile-studio__preview-orbit" />
            <small>PRÉVIA AO VIVO</small>
            <ProfileAvatar avatarDataUrl={profileAvatar} name={profileName || 'Você'} />
            <StyledProfileName style={profileStyle}>{profileName || 'Seu nome'}</StyledProfileName>
            <p>{roleLabel(profile.role)} · disponível</p>
            <div className="profile-studio__preview-call"><span><Icon name="audio" /></span><div><strong>Call da noite</strong><small><StyledProfileName style={profileStyle}>{profileName || 'Seu nome'}</StyledProfileName> está conversando</small></div><i /></div>
            <div className="profile-studio__preview-chat"><ProfileAvatar avatarDataUrl={profileAvatar} name={profileName || 'Você'} /><div><StyledProfileName style={profileStyle}>{profileName || 'Seu nome'}</StyledProfileName><p>Cheguei na call 👋</p></div></div>
          </aside>
          <section className="profile-studio__controls">
            <div className="profile-studio__section profile-studio__identity"><header><span>01</span><div><strong>Identidade básica</strong><small>Sua foto, nome visível e identificador único.</small></div></header><div><label className="channel-home__avatar-editor"><ProfileAvatar avatarDataUrl={profileAvatar} name={profileName || 'Você'} /><span><strong>Alterar foto</strong><small>PNG, JPG, WEBP ou GIF</small></span><input accept="image/gif,image/jpeg,image/png,image/webp" disabled={profileBusy} onChange={(event) => void chooseAvatar(event)} type="file" /></label><label className="profile-studio__name-field"><span>Nome visível</span><div><Icon name="users" /><input maxLength={48} onChange={(event) => setProfileName(event.target.value)} placeholder="Como devemos te chamar?" type="text" value={profileName} /><small>{profileName.length}/48</small></div></label><label className="profile-studio__name-field"><span>@Username</span><div><Icon name="users" /><input autoCapitalize="none" maxLength={25} onChange={(event) => setProfileUsername(event.target.value)} placeholder="seu_username" spellCheck={false} type="text" value={profileUsername} /><small>{profileUsername.replace(/^@/, '').length}/24</small></div></label></div></div>
            <div className="profile-studio__section"><header><span>02</span><div><strong>Tipografia</strong><small>Escolha a personalidade do seu nome.</small></div></header><div className="profile-studio__font-grid">{([['mono', 'Terminal', 'Precisa e técnica'], ['condensed', 'Impacto', 'Forte e direta'], ['rounded', 'Suave', 'Amigável e leve'], ['serif', 'Clássica', 'Elegante e editorial']] as const).map(([font, label, description]) => <button className={profileStyle.font === font ? 'is-active' : ''} key={font} onClick={() => setProfileStyle({ ...profileStyle, font })} type="button"><StyledProfileName style={{ ...profileStyle, font }}>{label}</StyledProfileName><small>{description}</small></button>)}</div></div>
            <div className="profile-studio__section"><header><span>03</span><div><strong>Cor e acabamento</strong><small>Um detalhe seu, visível sem prejudicar a leitura.</small></div></header><div className="profile-studio__color-row"><label><input aria-label="Cor personalizada" onChange={(event) => setProfileStyle({ ...profileStyle, color: event.target.value.toUpperCase() })} type="color" value={profileStyle.color} /><span>{profileStyle.color}</span></label><div>{['#B7F52B', '#64E9CE', '#83A7FF', '#C79AFF', '#FF8EB5', '#FFB86B', '#F2F4EF'].map((color) => <button aria-label={`Usar cor ${color}`} className={profileStyle.color === color ? 'is-active' : ''} key={color} onClick={() => setProfileStyle({ ...profileStyle, color })} style={{ '--swatch': color } as CSSProperties} type="button" />)}</div></div><div className="profile-studio__segmented">{([['none', 'Limpo'], ['glow', 'Glow'], ['shadow', 'Sombra'], ['outline', 'Contorno']] as const).map(([effect, label]) => <button className={profileStyle.effect === effect ? 'is-active' : ''} key={effect} onClick={() => setProfileStyle({ ...profileStyle, effect })} type="button">{label}</button>)}</div></div>
            <div className="profile-studio__section"><header><span>04</span><div><strong>Ritmo e destaque</strong><small>Ajustes finais para a sua assinatura.</small></div></header><div className="profile-studio__option-groups"><fieldset><legend>Peso</legend><div className="profile-studio__segmented">{([500, 600, 700] as const).map((weight) => <button className={profileStyle.weight === weight ? 'is-active' : ''} key={weight} onClick={() => setProfileStyle({ ...profileStyle, weight })} type="button">{weight === 500 ? 'Médio' : weight === 600 ? 'Forte' : 'Máximo'}</button>)}</div></fieldset><fieldset><legend>Espaçamento</legend><div className="profile-studio__segmented">{([['tight', 'Justo'], ['normal', 'Normal'], ['wide', 'Aberto']] as const).map(([spacing, label]) => <button className={profileStyle.spacing === spacing ? 'is-active' : ''} key={spacing} onClick={() => setProfileStyle({ ...profileStyle, spacing })} type="button">{label}</button>)}</div></fieldset><fieldset><legend>Selo</legend><div className="profile-studio__segmented">{([['none', 'Nenhum'], ['soft', 'Suave'], ['outline', 'Linha'], ['pill', 'Pílula']] as const).map(([badge, label]) => <button className={profileStyle.badge === badge ? 'is-active' : ''} key={badge} onClick={() => setProfileStyle({ ...profileStyle, badge })} type="button">{label}</button>)}</div></fieldset><fieldset><legend>Animação</legend><div className="profile-studio__segmented">{([['none', 'Parado'], ['breathe', 'Pulso'], ['spark', 'Brilho'], ['float', 'Flutuar']] as const).map(([animation, label]) => <button className={profileStyle.animation === animation ? 'is-active' : ''} key={animation} onClick={() => setProfileStyle({ ...profileStyle, animation })} type="button">{label}</button>)}</div></fieldset><label className="profile-studio__toggle"><input checked={profileStyle.casing === 'uppercase'} onChange={(event) => setProfileStyle({ ...profileStyle, casing: event.target.checked ? 'uppercase' : 'normal' })} type="checkbox" /><span /><div><strong>Usar caixa alta</strong><small>Deixa sua assinatura mais marcante.</small></div></label></div></div>
            {message && <div className="inline-error"><Icon name="warning" /><span>{message}</span></div>}
            <footer className="profile-studio__actions"><span><Icon name="eye" /> A prévia é exatamente como os outros verão.</span><div><button onClick={() => setView('home')} type="button">Cancelar</button><button disabled={profileBusy || !profileName.trim()} type="submit">{profileBusy ? 'Salvando…' : 'Salvar identidade'}</button></div></footer>
          </section>
        </form>
      </div>}
      {view === 'settings' && <AppSettingsScreen activitySharingEnabled={activitySharingEnabled} canHighQualityScreenShare={canHighQualityScreenShare} onActivitySharingChange={onActivitySharingChange} onClose={() => setView('home')} />}
    </section>
    {toast && <div aria-live="polite" className="app-toast"><span><Icon name="check" /></span><div><strong>Tudo certo</strong><p>{toast}</p></div><button aria-label="Fechar confirmação" onClick={() => setToast('')} type="button"><Icon name="x" /></button></div>}
  </main>
}
